### ISSUE TITLE
一个很奇怪的BUG，mapped-key-prefixes 这个值设置的比较复杂时，会导致加密的解密失效

### ISSUE THREAD

**Issue by quhaojian** [WhiteDG/mybatis-crypto#10]
mapped-key-prefixes 这个我设置为swsalary 后，查询的时候加密器的解密不触发了

**Comment by WhiteDG** [comment]
你这里说的解密不触发是指查询结果返回了密文而不是明文吗？

**Comment by quhaojian** [comment]
> 

不好意思 描述有点问题  是设置之后，存到数据库里面的是明文，而不是密文  
我打断点，加密器的加密不触发了

**Comment by WhiteDG** [comment]
可以贴一下你的代码吗？或者提供一个可复现的最小demo

**Comment by quhaojian** [comment]
> 可以贴一下你的代码吗？或者提供一个可复现的最小demo

项目是自己实现的IEncryptor
mapped-key-prefixes 由et设置为swsalary后
正常的用实体类保存或者修改 加密字段在数据库中从密文变成了明文了

自己调试发现 继承IEncryptor的类中的 encrypt 方法不走了， 查询时decrypt发放正常

**Comment by WhiteDG** [comment]
我自己测试没有复现，所以需要你提供多一点信息，你可以贴一下你的 mapper 和实体类，我猜测有问题的应该是这两部分。
