### ISSUE TITLE
mybatis的association一对一无法解密

### ISSUE THREAD

**Issue by mmdlsu** [WhiteDG/mybatis-crypto#12]
对象中的对象里面字段有@EncryptedField注解无法解密

**Comment by WhiteDG** [comment]
之前没考虑到 association，目前仅支持 association 中的 select。
我会尽快加上，感谢反馈。

**Comment by WhiteDG** [comment]
发布了一个快照版本 1.2.4-SNAPSHOT 支持了 association 和 collection，可以先用这个版本验证一下，后续再发布正式版。
使用时需要在对象字段上添加 @EncryptedField 注解。
