### ISSUE TITLE
使用提供的加解密类io.github.whitedg.mybatis.crypto.AES256Encryptor，无法正确查询

### ISSUE THREAD

**Issue by h00m00s00** [WhiteDG/mybatis-crypto#13]

**Comment by WhiteDG** [comment]
抱歉，文档没有补充相关说明，之前在 #1 这个 issue 中有做提到。
因为 mybatis-crypto-encryptors 中 AES256Encryptor 相同的明文每次加密生成的密文都是不一样的，所以无法用于查询。
