### ISSUE TITLE
优化问题

### ISSUE THREAD

**Issue by huyueyueTS** [WhiteDG/mybatis-crypto#15]
个人觉得AbsEncryptionPlugin类中的很多私有方法可以设值为public或protect级别，方便扩展，可以借鉴下模板模式。
现在的框架中针对业务场景想对方法进行扩展完全不行。只有将类全部拉下来重写。

**Comment by WhiteDG** [comment]
可以了解一下你是什么样的应用场景吗？

**Comment by huyueyueTS** [comment]
Mybatis plus BaseMapper中的 update 方法会默认带上@Param("et")，我如果想调这个方法并且加密的话必须将et做为前缀配置到前缀里面，但是我不能保证会影响其他功能（屎山项目），而且现在加密的字段相对很少，我可能更加倾向于加层判断（其实全局搜索发现不加也可以，只是图安心^_^），现在的代码中很多是private方法，导致我继承了AbsEncryptionPlugin也只能在interceptor中判断切面中的一些变量（statement之类的）。

关键是没必要将方法设置为private，不然抽象出来最多重载一个构造方法和接口方法，抽象出来也没意义，也不利于扩展。
您可以考虑一下这些方法的定义，封装之类的是否合适，很多方法、字段感觉都不太合适，很难去做扩展。
（PS：二次开发，屎山代码，场景可能不太适用。希望项目越来越多引用。）

**Comment by WhiteDG** [comment]
感谢您的建议，我觉得有一定的道理，后续我会考虑优化插件代码的设计。
因为 AbsEncryptionPlugin 本意不是给用户扩展用的（也不应该是 public 的），只是给 MybatisEncryptionPlugin 和 MybatisQueryEncryptionPlugin 继承的，方法都是 private 的原因也是一样。
