### ISSUE TITLE
在使用 mybatis-plus时候，使用queryWrapper里面的查询参数无法加密

### ISSUE THREAD

**Issue by liangxp** [WhiteDG/mybatis-crypto#21]
例如：
baseMapper.selectList(new LambdaQueryWrapper<GovCompany>().eq(GovCompany::getName, value)
                .eq(GovCompany::getDelFlag,"0"))
其中 name需要在查询的时候加密

**Comment by WhiteDG** [comment]
目前还不支持 mybatis-plus QueryWrapper

**Comment by liangxp** [comment]
谢谢
