### ISSUE TITLE
id属性抽在父类中的情况, java.lang.NoSuchFieldException: id

### ISSUE THREAD

**Issue by habyss** [WhiteDG/mybatis-crypto#3]
`class KeyFieldsProvider {
    private static final ConcurrentHashMap<String, List<Field>> CACHE = new ConcurrentHashMap<>();

    public static List<Field> get(MappedStatement mappedStatement, Object obj) {
        String id = mappedStatement.getId();
        return CACHE.computeIfAbsent(id, msId -> {
            String[] keyProperties = mappedStatement.getKeyProperties();
            if (keyProperties == null || keyProperties.length == 0) {
                return Collections.emptyList();
            }
            List<Field> fields = new ArrayList<>(keyProperties.length);
            try {
                for (String keyProperty : keyProperties) {
                    Field field = obj.getClass().getDeclaredField(keyProperty);
                    field.setAccessible(true);
                    fields.add(field);
                }
            } catch (NoSuchFieldException e) {
                throw new RuntimeException(e);
            }
            return fields;
        });
    }
}`
其中Field field = obj.getClass().getDeclaredField(keyProperty);会报错java.lang.NoSuchFieldException: id

**Comment by WhiteDG** [comment]
感谢反馈，这是没有处理父类字段导致的。
已经在 feature/V1.2 分支修复，可以使用 1.2-SNAPSHOT 版本看看还有没有问题，迟点会发布 1.2 正式版
