### ISSUE TITLE
insert 无法返回主键id

### ISSUE THREAD

**Issue by caizhixiang** [WhiteDG/mybatis-crypto#4]
这玩意儿很恶心，重置了原先mybatis 插入返回主键id的设置，很垃圾，最好不要用这东西

**Comment by WhiteDG** [comment]
> 这玩意儿很恶心，重置了原先mybatis 插入返回主键id的设置，很垃圾，最好不要用这东西

抱歉给您带来不好的体验，可以具体描述一下遇到的问题或者提供一个 demo 吗，我看看能不能解决。
mybatis-crypto-demo 中有 insert 的例子（io.github.whitedg.demo.controller.UserController#create），测试是可以返回主键 id 的。

**Comment by kevinjoy89** [comment]
1.1.0版本：insert中使用selectKey的情况，无法返回主键id无法返回
1.2.1版本：不开启keep-parameter的情况下，insert中使用selectKey的情况，能够正常返回主键id; 设置keep-parameter=true的情况下，无法返回主键id

**Comment by WhiteDG** [comment]
https://github.com/WhiteDG/mybatis-crypto/issues/6  已修复
