### ISSUE TITLE
1.1.0/1.2.1版本insert中使用selectKey时无法返回主键id

### ISSUE THREAD

**Issue by kevinjoy89** [WhiteDG/mybatis-crypto#6]
````xml
 <insert id="insert" parameterType="com.xxxx.entity.MemberLog">
    <!-- 插入时不设置ID值，数据库自增主键 -->
    insert into .... values ....
    <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Long">
      SELECT LAST_INSERT_ID()
    </selectKey>
</insert>
````
1.1.0版本：insert中使用selectKey的情况，主键id无法返回（insert标签再次设置keyProperty="id"时可以正常返回主键id）；
1.2.1版本：不开启keep-parameter的情况下，insert中使用selectKey的情况，能够正常返回主键id; 设置keep-parameter=true的情况下，无法返回主键id；

备注：不使用mybatis-crypto时以上示例代码补全后可以正常返回主键id

**Comment by WhiteDG** [comment]
感谢反馈，问题已修复，请帮忙使用 1.2.2 版本验证

**Comment by kevinjoy89** [comment]
已验证可以正常返回主键id
